#!/usr/bin/env bash
# Write a per-instance DAB target into resources/_generated_instance_target.yml
# so each DEFAULT_INSTANCE_ID gets its own Terraform state directory
# (``.databricks/bundle/<target>/``).
#
# Static targets ``dev`` / ``dev-lakebase`` in databricks.yml stay as-is for
# legacy deploys. Instance targets (``dev-lakebase-<id>``) are generated here
# and picked up via ``include: resources/*.yml``. Registry is always Lakebase.
#
# Usage (from repo root, after deploy.config.sh is sourced):
#   source scripts/_internal/_ensure-instance-target.sh
#   ensure_instance_target "$DAB_TARGET"
#
# Args to ensure_instance_target: <dab_target>

_GENERATED_TARGET_FILE="resources/_generated_instance_target.yml"

ensure_instance_target() {
    local target="${1:-}"
    if [[ -z "$target" ]]; then
        echo "ensure_instance_target: missing target" >&2
        return 1
    fi

    # Legacy unsuffixed targets are defined statically in databricks.yml.
    if [[ "$target" == "dev" || "$target" == "dev-lakebase" ]]; then
        rm -f "$_GENERATED_TARGET_FILE"
        return 0
    fi

    if [[ "$target" != dev-lakebase-* ]]; then
        echo "ensure_instance_target: unsupported target '${target}'" >&2
        echo "  expected: dev-lakebase | dev-lakebase-<id>  (registry is always Lakebase)" >&2
        echo "  (legacy Volume-only: pass -t dev — static target, no generation)" >&2
        return 1
    fi

    mkdir -p resources
    cat > "$_GENERATED_TARGET_FILE" <<EOF
# AUTO-GENERATED by scripts/_internal/_ensure-instance-target.sh — do not edit.
# Instance target for DEFAULT_INSTANCE_ID (Lakebase registry).
targets:
  ${target}:
    mode: development
    resources:
      apps:
        ontobricks_dev_app:
          resources:
            - name: postgres
              description: "Lakebase Autoscaling Postgres database for the OntoBricks registry"
              postgres:
                branch: projects/\${var.lakebase_project}/branches/\${var.lakebase_branch}
                database: projects/\${var.lakebase_project}/branches/\${var.lakebase_branch}/databases/\${var.lakebase_database_resource_segment}
                permission: "CAN_CONNECT_AND_CREATE"
            - name: neo4j-password
              description: "Databricks Apps secret holding the Neo4j Bolt password"
              secret:
                scope: \${var.neo4j_secret_scope}
                key: neo4j-password
                permission: READ
        mcp_ontobricks_app:
          resources:
            - name: postgres
              description: "Lakebase Autoscaling Postgres database for the OntoBricks registry"
              postgres:
                branch: projects/\${var.lakebase_project}/branches/\${var.lakebase_branch}
                database: projects/\${var.lakebase_project}/branches/\${var.lakebase_branch}/databases/\${var.lakebase_database_resource_segment}
                permission: "CAN_CONNECT_AND_CREATE"
EOF
}
