#!/usr/bin/env bash
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

REPORTS_DIR="tests/reports"
TIMESTAMP="$(date '+%Y-%m-%d_%H-%M-%S')"
REPORT_FILE="${REPORTS_DIR}/${TIMESTAMP}_tests_reports.md"
VENV_PYTHON=".venv/bin/python"

mkdir -p "$REPORTS_DIR"

if [[ ! -x "$VENV_PYTHON" ]]; then
    echo "ERROR: Virtual environment not found at $VENV_PYTHON"
    echo "Run 'uv sync --dev' first."
    exit 1
fi

echo "============================================"
echo " OntoBricks Test Campaign"
echo " $(date '+%Y-%m-%d %H:%M:%S')"
echo "============================================"
echo ""

RAW_OUTPUT=$(mktemp)
trap 'rm -f "$RAW_OUTPUT"' EXIT

echo "[1/3] Running test suite with coverage..."
$VENV_PYTHON -m pytest tests/ -v --tb=short \
    --cov=src/app --cov-report=term-missing \
    2>&1 | tee "$RAW_OUTPUT"
PYTEST_EXIT=${PIPESTATUS[0]}
echo ""

# --- Extract summary numbers using awk (macOS compatible) ---
SUMMARY_LINE=$(grep -E '(passed|failed|error|warning)' "$RAW_OUTPUT" | tail -1)
TOTAL=$(echo "$SUMMARY_LINE" | awk '{for(i=1;i<=NF;i++) if($i=="passed" || $i=="passed,") print $(i-1)}')
FAILED=$(echo "$SUMMARY_LINE" | awk '{for(i=1;i<=NF;i++) if($i=="failed" || $i=="failed,") print $(i-1)}')
ERRORS=$(echo "$SUMMARY_LINE" | awk '{for(i=1;i<=NF;i++) if(index($i,"error")) print $(i-1)}')
WARNINGS=$(echo "$SUMMARY_LINE" | awk '{for(i=1;i<=NF;i++) if(index($i,"warning")) print $(i-1)}')
DURATION=$(echo "$SUMMARY_LINE" | grep -oE '[0-9]+\.[0-9]+s' | tail -1)

TOTAL=${TOTAL:-0}; FAILED=${FAILED:-0}; ERRORS=${ERRORS:-0}; WARNINGS=${WARNINGS:-0}; DURATION=${DURATION:-?}

COLLECTED=$(grep 'collected' "$RAW_OUTPUT" | grep -oE '[0-9]+ items' | grep -oE '[0-9]+' || echo 0)

COV_LINE=$(awk '/^TOTAL / {print}' "$RAW_OUTPUT" | head -1)
COV_STMTS=$(echo "$COV_LINE" | awk '{print $2}')
COV_MISS=$(echo "$COV_LINE" | awk '{print $3}')
COV_PCT=$(echo "$COV_LINE" | awk '{print $4}')
COV_STMTS=${COV_STMTS:-?}; COV_MISS=${COV_MISS:-?}; COV_PCT=${COV_PCT:-?}

# --- Per-file results ---
echo "[2/3] Collecting per-file results..."

PER_FILE_DATA=$(mktemp)
trap 'rm -f "$RAW_OUTPUT" "$PER_FILE_DATA"' EXIT

grep -E '::.*(PASSED|FAILED|ERROR)' "$RAW_OUTPUT" | \
    awk -F '::' '{
        file=$1; gsub(/^tests\//, "", file); gsub(/^ +/, "", file)
    }' > /dev/null

# Build per-file stats with awk
awk -F '::' '
/::.*(PASSED|FAILED|ERROR)/ {
    file = $1
    gsub(/^tests\//, "", file)
    gsub(/^ +/, "", file)
    if (match($0, / PASSED/)) pass[file]++
    else if (match($0, / FAILED/)) fail[file]++
    else if (match($0, / ERROR/))  err[file]++
}
END {
    for (f in pass) if (!(f in fail) && !(f in err)) fail[f]=0
    for (f in fail) if (!(f in pass)) pass[f]=0
    for (f in err)  if (!(f in pass)) pass[f]=0

    for (f in pass) {
        p = pass[f]+0; fl = (f in fail ? fail[f]+0 : 0); e = (f in err ? err[f]+0 : 0)
        status = (fl > 0 || e > 0) ? "FAIL" : "PASS"
        printf "| `%s` | %d | %d | %d | %s |\n", f, p, fl, e, status
    }
}' "$RAW_OUTPUT" | sort > "$PER_FILE_DATA"

# --- Failure details ---
FAIL_DETAILS=""
if [[ "$FAILED" -gt 0 ]] || [[ "$ERRORS" -gt 0 ]]; then
    FAIL_DETAILS=$(awk '/^=+ short test summary/,0' "$RAW_OUTPUT" | head -50 || true)
fi

# --- Coverage module table ---
COV_MODULES=$(awk '/^src\/app\/.*[0-9]+%/ {print}' "$RAW_OUTPUT" | sort -t'%' -k1 -rn | head -40)

# --- Pytest and Python version ---
PY_VERSION=$($VENV_PYTHON --version 2>&1 | awk '{print $2}')
PT_VERSION=$($VENV_PYTHON -m pytest --version 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)

echo "[3/3] Generating report -> $REPORT_FILE"

cat > "$REPORT_FILE" <<REPORT_EOF
# OntoBricks Test Campaign Report

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Platform:** $(uname -s) -- Python ${PY_VERSION}, pytest ${PT_VERSION}
**Exit code:** ${PYTEST_EXIT}

---

## Summary

| Metric | Value |
|--------|-------|
| **Total collected** | ${COLLECTED} |
| **Passed** | ${TOTAL} |
| **Failed** | ${FAILED} |
| **Errors** | ${ERRORS} |
| **Warnings** | ${WARNINGS} |
| **Duration** | ${DURATION} |
| **Coverage** | ${COV_PCT} (${COV_STMTS} stmts, ${COV_MISS} missed) |

---

## Results by Test File

| File | Passed | Failed | Errors | Status |
|------|--------|--------|--------|--------|
$(cat "$PER_FILE_DATA")
REPORT_EOF

if [[ -n "$FAIL_DETAILS" ]]; then
cat >> "$REPORT_FILE" <<FAIL_EOF

---

## Failure Details

\`\`\`
${FAIL_DETAILS}
\`\`\`
FAIL_EOF
fi

cat >> "$REPORT_FILE" <<COV_EOF

---

## Coverage by Module

\`\`\`
${COV_MODULES}
\`\`\`

**Total:** ${COV_STMTS} statements, ${COV_MISS} missed, **${COV_PCT}** coverage

---

*Report generated by run_tests.sh on $(date '+%Y-%m-%d %H:%M:%S')*
COV_EOF

echo ""
echo "============================================"
echo " Campaign Complete"
echo "============================================"
echo " Passed:   $TOTAL"
echo " Failed:   $FAILED"
echo " Errors:   $ERRORS"
echo " Coverage: $COV_PCT"
echo " Report:   $REPORT_FILE"
echo "============================================"

exit $PYTEST_EXIT
